title: Problem Journey
email: user@example.com
description: >-
  Documenting my daily learning journey.
baseurl: "/problem-solving"
url: "https://yourusername.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  problems:
    output: true
    permalink: /problems/:slug/

defaults:
  - scope:
      path: ""
      type: "problems"
    values:
      layout: "problem"

markdown: kramdown
highlighter: rouge
